import { Link } from 'react-router-dom';
import heroImage from '../../assets/images/polomolok-hero-bg.jpg';
import { usePageTitle } from '../hooks/usePageTitle';

export function BuyingProcessPage() {
  usePageTitle('Buying process | renoleads');
  return <><SupportHero eyebrow="A practical checklist" title="Buying a lot starts with better questions." text="Use renoleads to narrow your search, prepare for a conversation, and decide whether a site visit is the right next step."/><section className="support-content"><div className="container"><div className="section-header" data-reveal="up"><span className="section-eyebrow">Four steps</span><h2>From first look to site visit.</h2></div><div className="process-steps">{[['1','Shortlist','Save published lots you want to compare later.'],['2','Review','Read the published price, area, project placement, location, and description.'],['3','Ask','Request current photos, title and survey information, boundaries, access, utilities, and final terms.'],['4','Visit','Inspect the route and the land, then compare what you observed with the documents and terms provided.']].map(([number,title,text]) => <Step key={number} number={number} title={title} text={text}/>)}</div><div className="checklist-grid"><div data-reveal="left"><h2>Before you commit</h2><ul className="checklist"><li>Confirm ownership and document status with appropriate professionals.</li><li>Inspect access, drainage, slope, utilities, and surrounding activity in person.</li><li>Ask how lot boundaries and measurements were established.</li><li>Get final pricing and payment terms in writing before proceeding.</li></ul></div><div className="visit-note" data-reveal="right"><span className="section-eyebrow">Site visit note</span><h2>Listings are a starting point.</h2><p>Photos and descriptions can help you decide what to inspect, but they do not replace an on-site review or qualified advice.</p></div></div></div></section><SupportCta/></>;
}

export function WhyPolomolokPage() {
  usePageTitle('Why Polomolok | renoleads');
  return <><SupportHero eyebrow="Local context" title="Why Polomolok?" text="A working agricultural landscape with town, road, and community context. Whether a lot fits depends on your intended use and what you can verify."/><section className="support-content"><div className="container support-grid"><div data-reveal="left"><span className="section-eyebrow">Three useful questions</span><h2>Look beyond the headline.</h2><p>Land decisions are easier when a listing helps you ask better questions. Use these prompts as a conversation starter, not as a guarantee about any specific lot.</p></div><div className="support-reasons" data-reveal="right"><Reason number="01" title="What do you plan to do with the land?" text="Start with your intended use and verify whether the property, access, utilities, and applicable rules fit that plan."/><Reason number="02" title="What is easy to reach?" text="Road access, nearby services, terrain, and travel conditions shape the practical experience of owning land. Inspect the route in person."/><Reason number="03" title="What can you verify?" text="Request current photos, ownership and survey information, boundaries, final terms, and utility details. Have qualified professionals review anything material to your decision."/></div></div></section><section className="property-strip-section"><div className="container"><div className="section-header section-header-inline" data-reveal="up"><div><span className="section-eyebrow">Ready to compare?</span><h2>See the currently published inventory.</h2></div><Link className="btn btn-primary btn-sm" to="/properties">Browse inventory</Link></div></div></section><SupportCta/></>;
}

export function PrivacyPage() {
  usePageTitle('Privacy | renoleads');
  return <article className="legal-content container" data-reveal="up"><span className="section-eyebrow">Site information</span><h1>Privacy Notice</h1><p className="legal-updated">Version: 2026-08-22 · Last updated: August 22, 2026</p><p>renoleads presents published land-lot inventory and sends buyer inquiries to the shared NJ125 operations system.</p><h2>Information you provide</h2><p>If you submit an inquiry, the form may collect your name, mobile number, email address, selected property, inquiry type, preferred contact method, preferred date, and message. NJ125 uses this information to respond to your request and manage the related lead workflow.</p><h2>Consent and inquiry records</h2><p>An inquiry is submitted only after you acknowledge this Privacy Notice. The backend records the notice version used for that submission together with the inquiry record.</p><h2>Local device storage</h2><p>renoleads stores only saved lot IDs and recently viewed lot IDs in local browser storage. Inquiry names, mobile numbers, email addresses, messages, and other inquiry details are not buffered in local storage.</p><h2>Attribution</h2><p>The site may retain first-touch landing page, referrer, and UTM campaign parameters in session storage so NJ125 can understand how an inquiry reached renoleads. Session storage normally ends when the browser session ends.</p><h2>Service provider</h2><p>The public website sends property-feed and inquiry requests to the NJ125 Supabase Edge API. renoleads does not directly expose NJ125 database tables to the browser. Firebase is used only to host the compiled public website.</p><h2>Property information</h2><p>Listing descriptions, photos, prices, areas, and location information should be reviewed and independently verified before any purchase decision.</p><h2>Contact</h2><p>For questions about this notice, use the <Link className="text-link" to="/contact">renoleads inquiry form</Link>.</p></article>;
}

function SupportHero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) {
  return <section className="support-hero"><img className="support-hero-bg" src={heroImage} alt="" aria-hidden="true"/><div className="container" data-reveal="up"><span className="hero-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>;
}

function SupportCta() {
  return <section className="support-cta"><div className="container" data-reveal="scale"><h2>Ready to compare a few lots?</h2><p>Open the published inventory or send a focused question.</p><Link className="btn btn-accent" to="/properties">Browse available lots</Link></div></section>;
}

function Step({ number, title, text }: { number: string; title: string; text: string }) {
  return <div className="process-step" data-reveal="up"><span className="process-step-number">{number}</span><div><h3>{title}</h3><p>{text}</p></div></div>;
}

function Reason({ number, title, text }: { number: string; title: string; text: string }) {
  return <article className="support-reason"><span className="support-reason-number">{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>;
}
